// Generated by CoffeeScript 1.6.3
(function() {

  $(document).ready(function() {
    return $('#play').click(function(e) {
      $('#content').append("<h1>Hello World</h1>");
    });
  });

}).call(this);
